# Nightfox
#
# UI / Environment
#   Background (bg1): #192330  Dark bg (bg0): #131a24
#   Foreground (fg1): #cdcecf  Comment: #526175
#   Selection (sel0): #2b3b51  Search / popup sel (sel1): #3c5372
#
# Base Palette (dim / base / bright)
#   Black:   #393b44    Red:     #c94f6d
#   Green:   #81b29a    Yellow:  #dbc074
#   Blue:    #719cd6    Magenta: #9d79d6
#   Cyan:    #63cdcf    White:   #cdcecf
#   Orange:  #f4a261    Pink:    #d67ad2

set -g status-style "bg=#192330,fg=#cdcecf"
set -g pane-border-style "fg=#283A4F"
set -g pane-active-border-style "fg=#719cd6"
set -g window-status-current-style "bg=#283A4F,fg=#719cd6,bold"
set -g window-status-style "fg=#4a5d6e"
